//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EP.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class DesignationTable
    {
        public DesignationTable()
        {
            this.EmployeeTables = new HashSet<EmployeeTable>();
        }
    
        public int DesignationId { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<EmployeeTable> EmployeeTables { get; set; }
    }
}
