
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EP.Modal
{

using System;
    using System.Collections.Generic;
    
public partial class EarnedPoint
{

    public long FromEmployeeId { get; set; }

    public long ToEmployeeId { get; set; }

    public int Points { get; set; }

    public System.DateTime DateGiven { get; set; }

    public Nullable<bool> IsRedeemed { get; set; }

    public Nullable<System.DateTime> DateRedeemed { get; set; }

    public string Reason { get; set; }

}

}
