//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EP.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTable
    {
        public EmployeeTable()
        {
            this.LoginTables = new HashSet<LoginTable>();
        }
    
        public long EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public int DesignationId { get; set; }
        public string ProfilePic { get; set; }
        public long TotalEarnedPoints { get; set; }
    
        public virtual DesignationTable DesignationTable { get; set; }
        public virtual ICollection<LoginTable> LoginTables { get; set; }
    }
}
