
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EP.Modal
{

using System;
    using System.Collections.Generic;
    
public partial class EmployeeTable
{

    public long LoginId { get; set; }

    public string EmployeeName { get; set; }

    public int DesignationId { get; set; }

    public string ProfilePic { get; set; }

    public Nullable<long> TotalEarnedPoints { get; set; }

    public System.DateTime DateCreated { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public Nullable<System.DateTime> DateDeleted { get; set; }

    public Nullable<long> TotalRedeemedPoints { get; set; }



    public virtual DesignationTable DesignationTable { get; set; }

    public virtual LoginTable LoginTable { get; set; }

}

}
