
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EP.Modal
{

using System;
    using System.Collections.Generic;
    
public partial class LoginTable
{

    public long LoginId { get; set; }

    public string EmployeeId { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string Contact { get; set; }



    public virtual EmployeeTable EmployeeTable { get; set; }

}

}
